services:

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: my_secure_password
            POSTGRES_DB: mydb
        ports:
            - 5432:5432
